# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window_.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(871, 634)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.check_camera = QtWidgets.QPushButton(self.centralwidget)
        self.check_camera.setGeometry(QtCore.QRect(30, 440, 151, 31))
        self.check_camera.setObjectName("check_camera")
        self.capture_Faces = QtWidgets.QPushButton(self.centralwidget)
        self.capture_Faces.setGeometry(QtCore.QRect(300, 440, 151, 31))
        self.capture_Faces.setObjectName("capture_Faces")
        self.Train_images = QtWidgets.QPushButton(self.centralwidget)
        self.Train_images.setGeometry(QtCore.QRect(550, 440, 171, 31))
        self.Train_images.setObjectName("Train_images")
        self.Attendence = QtWidgets.QPushButton(self.centralwidget)
        self.Attendence.setGeometry(QtCore.QRect(40, 520, 141, 31))
        self.Attendence.setObjectName("Attendence")
        self.quit = QtWidgets.QPushButton(self.centralwidget)
        self.quit.setGeometry(QtCore.QRect(300, 522, 151, 31))
        self.quit.setObjectName("quit")
        self.camera_label = QtWidgets.QLabel(self.centralwidget)
        self.camera_label.setGeometry(QtCore.QRect(6, 3, 801, 411))
        self.camera_label.setObjectName("camera_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 871, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.check_camera.setText(_translate("MainWindow", "Check Camera "))
        self.capture_Faces.setText(_translate("MainWindow", "Capture Faces "))
        self.Train_images.setText(_translate("MainWindow", "Train images "))
        self.Attendence.setText(_translate("MainWindow", "Attendance "))
        self.quit.setText(_translate("MainWindow", "Quit "))
        self.camera_label.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
